### 1. What is NumPy?
##### Answer: NumPy is a Python library used for working with arrays. It also provides functions for working in the domain of linear algebra, Fourier transform, and matrices.

### 2. How do you install NumPy?
##### Answer: You can install NumPy using pip:

`pip install numpy`

### 3. How do you import NumPy?
##### Answer: You can import NumPy using the following command:

`import numpy as np`

### 4. How do you create a NumPy array?
##### Answer: You can create a NumPy array using the `np.array()` function:

In [ ]:
import numpy as np 
arr = np.array([1, 2, 3])
arr

### 5. How do you create an array with all zeros?
##### Answer: Use the `np.zeros()`  function:

In [2]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 6. How do you create an array with all ones?
##### Answer: Use the np.ones() function:

In [3]:
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 7. How do you create an array with a specific shape filled with a specific value?
##### Answer: Use the np.full() function:

In [4]:
full_array = np.full((3, 3), 7)
full_array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### 8. How do you create an identity matrix?
##### Answer: Use the np.eye() function:

In [5]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 9. How do you create an array with random values?
##### Answer: Use the np.random.random() function:

In [6]:
random_array = np.random.random((3, 3))
random_array

array([[0.27550318, 0.02561761, 0.96662628],
       [0.71454816, 0.36573553, 0.74646071],
       [0.5595776 , 0.70665264, 0.55570942]])

### 10. How do you create an array with a range of values?

In [7]:
range_array = np.arange(10, 20)
random_array

array([[0.27550318, 0.02561761, 0.96662628],
       [0.71454816, 0.36573553, 0.74646071],
       [0.5595776 , 0.70665264, 0.55570942]])

### 11. How do you create an array with evenly spaced values between two values?

In [8]:
linspace_array = np.linspace(0, 1, 5)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 12. How do you reshape an array?

In [9]:
reshaped_array = np.array([1, 2, 3, 4, 5, 6]).reshape((2, 3))
reshaped_array

array([[1, 2, 3],
       [4, 5, 6]])

### 13. How do you get the shape of an array?

In [10]:
array_shape = arr.shape
array_shape

(3,)

### 14. How do you get the data type of an array?

In [12]:
array_dtype = arr.dtype
array_dtype

dtype('int32')

### 15. How do you change the data type of an array?

In [13]:
float_array = arr.astype(np.float32)
float_array

array([1., 2., 3.], dtype=float32)

### 16. How do you find the maximum value in an array?


In [14]:
max_value = arr.max()
max_value

3

### 17. How do you find the minimum value in an array?

In [15]:
min_value = arr.min()
min_value

1

### 18. How do you find the index of the maximum value in an array? 

In [16]:
max_index = arr.argmax()
max_index

2

### 19. How do you find the index of the minimum value in an array?


In [17]:
total_sum = arr.sum()
total_sum

6

### 21. How do you get the mean of all elements in an array?

In [18]:
mean_value = arr.mean()
mean_value

2.0

### 22. How do you get the standard deviation of all elements in an array?

In [19]:
std_value = arr.std()
std_value

0.816496580927726

### 23. How do you get the median of all elements in an array?

In [20]:
median_value = np.median(arr)
median_value

2.0

### 24. How do you get the transpose of a matrix?

In [21]:
transposed_matrix = arr.T
transposed_matrix

array([1, 2, 3])

### 25. How do you flatten a multi-dimensional array?

In [22]:
flattened_array = arr.flatten()
flattened_array

array([1, 2, 3])

### 26. How do you concatenate two arrays?

In [24]:
arr1=np.array([1,2,3,4,5,6])

In [25]:
arr2=np.array([7,8,9,10,11,12])

In [27]:
concatenated_array = np.concatenate((arr1, arr2), axis=0)
concatenated_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 27. How do you stack arrays vertically?

In [29]:
vstacked_array = np.vstack((arr1, arr2))
vstacked_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### 28. How do you stack arrays horizontally?

In [30]:
hstacked_array = np.hstack((arr1, arr2))
hstacked_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 29. How do you split an array into multiple sub-arrays? 

In [31]:
split_arrays = np.split(arr, 3)
split_arrays

[array([1]), array([2]), array([3])]

### 30. How do you save a NumPy array to a file?

In [32]:
np.save('array.npy', arr)

### 31. How do you load a NumPy array from a file?

In [ ]:
arr = np.load('array.npy')

### 32. How do you save a NumPy array to a text file?

np.savetxt('array.txt', arr)

### 33. How do you load a NumPy array from a text file?

arr = np.loadtxt('array.txt')

### 34. How do you generate random integers within a specific range?

In [36]:
random_integers = np.random.randint(10, 20, size=(3, 3))
random_integers

array([[12, 10, 14],
       [10, 18, 15],
       [15, 10, 17]])

### 35. How do you shuffle the elements of an array?

In [37]:
np.random.shuffle(arr)

### 36. How do you find unique elements in an array?

In [38]:
unique_elements = np.unique(arr)
unique_elements

array([1, 2, 3])

### 37. How do you count the occurrences of each unique element in an array? 

In [39]:
unique_elements, counts = np.unique(arr, return_counts=True)
unique_elements

array([1, 2, 3])

### 38. How do you compute the dot product of two arrays? 

In [40]:
dot_product = np.dot(arr1, arr2)
dot_product

217

### 39. How do you compute the cross product of two arrays?

In [44]:
a1, b1 = 1, 2  
a2, b2 = 3, 4  
arr1 = np.array([a1, b1])
arr2 = np.array([a2, b2])
cross_product = np.cross(arr1, arr2)
cross_product

array(-2)

### 40. How do you compute the inverse of a matrix? 

In [50]:
arr = np.array([[4, 7],[2, 5]])
inverse_matrix = np.linalg.inv(arr)
arr


array([[4, 7],
       [2, 5]])

In [51]:
inverse_matrix

array([[ 0.83333333, -1.16666667],
       [-0.33333333,  0.66666667]])

### 41. How do you compute the determinant of a matrix?

In [52]:
determinant = np.linalg.det(arr)
determinant

6.0

### 42. How do you compute the eigenvalues and eigenvectors of a matrix?

In [55]:
eigenvalues, eigenvectors = np.linalg.eig(arr)
eigenvalues,eigenvectors

(array([0.72508278, 8.27491722]),
 array([[-0.9057736 , -0.85343697],
        [ 0.42376194, -0.52119606]]))

### 43. How do you perform element-wise addition of two arrays? 

In [63]:
array1=np.array([[12,45,87,46],[23,67,43,67]])
array2=np.array([[32,45,65,43],[78,49,67,90]])

In [64]:
sum_array = array1 + array2
sum_array

array([[ 44,  90, 152,  89],
       [101, 116, 110, 157]])

### Substraction 


In [65]:
diff_array = array1 - array2
diff_array

array([[-20,   0,  22,   3],
       [-55,  18, -24, -23]])

### # Multiplication

In [66]:
prod_array = array1 * array2
prod_array

array([[ 384, 2025, 5655, 1978],
       [1794, 3283, 2881, 6030]])

###  Division

In [67]:
div_array = array1 / array2
div_array

array([[0.375     , 1.        , 1.33846154, 1.06976744],
       [0.29487179, 1.36734694, 0.64179104, 0.74444444]])

### Matrix Multiplication

## dot product 

In [68]:
dot_product = np.dot(array1, array2.T)
dot_product


array([[10042, 13110],
       [ 9427, 13988]])

### Matrix Multiplication (using @ operator)

In [69]:
matrix_product = array1 @ array2.T
matrix_product

array([[10042, 13110],
       [ 9427, 13988]])

###  Element-Wise Operations

Exponentiation:

In [70]:
exp_array = np.power(array1, 2)
exp_array


array([[ 144, 2025, 7569, 2116],
       [ 529, 4489, 1849, 4489]], dtype=int32)

Square Root

In [71]:
sqrt_array = np.sqrt(array1)
sqrt_array


array([[3.46410162, 6.70820393, 9.32737905, 6.78232998],
       [4.79583152, 8.18535277, 6.55743852, 8.18535277]])

Logarithm

In [72]:
log_array = np.log(array1)
log_array

array([[2.48490665, 3.80666249, 4.46590812, 3.8286414 ],
       [3.13549422, 4.20469262, 3.76120012, 4.20469262]])

Element-Wise Comparison

In [74]:
greater_than = array1 > array2
greater_than

array([[False, False,  True,  True],
       [False,  True, False, False]])

In [75]:
less_than = array1 < array2
less_than

array([[ True, False, False, False],
       [ True, False,  True,  True]])

Equality

In [76]:
equal_to = array1 == array2
equal_to

array([[False,  True, False, False],
       [False, False, False, False]])

### Agregation 

Sum Along Axis

In [79]:
sum_along_axis0 = np.sum(array1, axis=0)
sum_along_axis0

array([ 35, 112, 130, 113])

In [78]:
sum_along_axis1 = np.sum(array1, axis=1)
sum_along_axis1

array([190, 200])

Cumulative Sum

In [80]:
cumsum_array = np.cumsum(array1)
cumsum_array

array([ 12,  57, 144, 190, 213, 280, 323, 390])

Product Along Axis

In [82]:
prod_along_axis0 = np.prod(array1, axis=0)
prod_along_axis0

array([ 276, 3015, 3741, 3082])

In [84]:
prod_along_axis1 = np.prod(array1, axis=1)
prod_along_axis1

array([2161080, 4439621])

### Statistical Functions

Variance:

In [85]:
variance_array = np.var(array1)
variance_array

524.6875

Standard Deviation

In [86]:
std_dev_array = np.std(array1)
std_dev_array

22.90605815062906

Logical Operations

Logical AND

In [87]:
logical_and = np.logical_and(array1 > 20, array2 < 50)
logical_and

array([[False,  True, False,  True],
       [False,  True, False, False]])

Logical OR

In [88]:
logical_or = np.logical_or(array1 > 20, array2 < 50)
logical_or


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Logical NOT

In [89]:
logical_not = np.logical_not(array1 > 20)
logical_not


array([[ True, False, False, False],
       [False, False, False, False]])

### Array Manipulation
 

Flatten

In [90]:
flattened_array = array1.flatten()
flattened_array

array([12, 45, 87, 46, 23, 67, 43, 67])

Reshape

In [91]:
reshaped_array = array1.reshape((4, 2))
reshaped_array

array([[12, 45],
       [87, 46],
       [23, 67],
       [43, 67]])

Transpose

In [92]:
transposed_array = array1.T
transposed_array

array([[12, 23],
       [45, 67],
       [87, 43],
       [46, 67]])

###  Matrix Functions

In [94]:
square_matrix = np.array([[1, 2], [3, 4]])
inv_matrix = np.linalg.inv(square_matrix)
inv_matrix


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [95]:
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)
eigenvalues

array([-0.37228132,  5.37228132])

In [96]:
original_array = np.arange(16)  
square_matrix = original_array.reshape((4, 4)) 
square_matrix


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
array1 = np.array([[12, 45, 87, 46], [23, 67, 43, 67]])
array2 = np.array([[32, 45, 65, 43], [78, 49, 67, 90]])

In [99]:
first_row_array1 = array1[0, :]
first_row_array1

array([12, 45, 87, 46])

In [100]:
second_col_array2 = array2[:, 1]
second_col_array2

array([45, 49])

In [101]:
step_slice1 = array1[0, ::2]
step_slice1

array([12, 87])

In [102]:
step_slice2 = array2[::2, :]
step_slice2

array([[32, 45, 65, 43]])

In [103]:
last_row_array1 = array1[-1, :]
last_row_array1

array([23, 67, 43, 67])

In [104]:
last_col_array2 = array2[:, -1]
last_col_array2

array([43, 90])

In [105]:
submatrix1 = array1[:2, :2]
submatrix1

array([[12, 45],
       [23, 67]])

In [106]:
submatrix2 = array2[0:2, 2:4]
submatrix2

array([[65, 43],
       [67, 90]])

In [107]:
boolean_slice1 = array1[array1 > 50]
boolean_slice1

array([87, 67, 67])

In [108]:
condition_slice2 = array2[array2[:, 1] < 50, :]
condition_slice2

array([[32, 45, 65, 43],
       [78, 49, 67, 90]])

In [109]:
condition_slice1 = array1[array1[:, 0] > 20, :]
condition_slice1

array([[23, 67, 43, 67]])

In [110]:
specific_element_array1 = array1[1, 2]
specific_element_array1

43

In [111]:
center_submatrix1 = array1[0:2, 1:3]
center_submatrix1

array([[45, 87],
       [67, 43]])

In [112]:
center_submatrix2 = array2[0:2, 1:3]
center_submatrix2

array([[45, 65],
       [49, 67]])

In [113]:
rows_greater_than_30 = array1[np.all(array1 > 30, axis=1), :]
rows_greater_than_30

array([], shape=(0, 4), dtype=int32)

In [114]:
cols_less_than_70 = array2[:, np.all(array2 < 70, axis=0)]
cols_less_than_70

array([[45, 65],
       [49, 67]])

In [115]:
mask = array1 < 50
masked_array1 = np.where(mask, 0, array1)
masked_array1

array([[ 0,  0, 87,  0],
       [ 0, 67,  0, 67]])

In [116]:
row_indices = np.array([0, 1])
col_indices = np.array([1, 2])
advanced_indexing = array1[row_indices, col_indices]
advanced_indexing

array([45, 43])

In [117]:
reshaped_slice2 = array2[0:2, 2:4].reshape(4, 1)
reshaped_slice2

array([[65],
       [43],
       [67],
       [90]])

In [118]:
upper_triangle_array1 = np.triu(array1)
upper_triangle_array1

array([[12, 45, 87, 46],
       [ 0, 67, 43, 67]])

In [119]:
lower_triangle_array2 = np.tril(array2)
lower_triangle_array2

array([[32,  0,  0,  0],
       [78, 49,  0,  0]])

In [120]:
rows_sum_greater_than_100 = array1[np.sum(array1, axis=1) > 100, :]
rows_sum_greater_than_100

array([[12, 45, 87, 46],
       [23, 67, 43, 67]])

In [121]:
cols_sum_less_than_150 = array2[:, np.sum(array2, axis=0) < 150]
cols_sum_less_than_150

array([[32, 45, 65, 43],
       [78, 49, 67, 90]])

In [122]:
rows_indices = [0, 1]
cols_indices = [1, 2]
fancy_indexing = array1[rows_indices, cols_indices]
fancy_indexing

array([45, 43])

In [123]:
mask = np.array([[True, False, True, False], [False, True, False, True]])
masked_array1 = array1[mask]
masked_array1

array([12, 87, 67, 67])

In [124]:
reversed_axis_array1 = array1[::-1, ::-1]
reversed_axis_array1

array([[67, 43, 67, 23],
       [46, 87, 45, 12]])

In [125]:
mean_array2 = np.mean(array2)
elements_greater_than_mean = array2[array2 > mean_array2]
elements_greater_than_mean

array([65, 78, 67, 90])

In [126]:
submatrix_and_reshape = array2[0:2, 2:4].reshape(4,)
submatrix_and_reshape

array([65, 43, 67, 90])